In [3]:
import pandas as pd

In [4]:
beer_df = pd.read_csv('BeerProject.csv')
beer_df

,beer_ABV,beer_beerId,beer_brewerId,beer_name,beer_style,review_appearance,review_palette,review_overall,review_taste,review_profileName,review_aroma,review_text,review_time
0,5.0,47986,10325,Sausa Weizen,Hefeweizen,2.5,2.0,1.5,1.5,stcules,1.5,A lot of foam. But a lot. In the smell some ba...,1234817823
1,6.2,48213,10325,Red Moon,English Strong Ale,3.0,2.5,3.0,3.0,stcules,3.0,"Dark red color, light beige foam, average. In ...",1235915097
2,6.5,48215,10325,Black Horse Black Beer,Foreign / Export Stout,3.0,2.5,3.0,3.0,stcules,3.0,"Almost totally black. Beige foam, quite compac...",1235916604
3,5.0,47969,10325,Sausa Pils,German Pilsener,3.5,3.0,3.0,2.5,stcules,3.0,"Golden yellow color. White, compact foam, quit...",1234725145
4,7.7,64883,1075,Cauldron DIPA,American Double / Imperial IPA,4.0,4.5,4.0,4.0,johnmichaelsen,4.5,"According to the website, the style for the Ca...",1293735206
...,...,...,...,...,...,...,...,...,...,...,...,...,...
528865,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.0,4.0,3.5,orangemoustache,4.0,"A-pours a reddish amber that looks very nice,l...",1205212721
528866,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.5,3.0,3.0,MisterStout,3.0,I don't really have anything special to say ab...,1203490783
528867,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,4.0,4.5,4.0,meechum,4.5,Had this on tap at Vreny's Beirgarten A - Came...,1201320897
528868,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.0,4.0,4.0,Dodo2step,4.5,"Purchased at Market Cross Pub in carlisle, PA....",1201215290
528869,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,4.0,4.0,4.0,jenbys2001,4.0,"I ordered a mug of this beer at Schnitzelhaus,...",1200336367

In [5]:
beer_df.dtypes

beer_ABV              float64
beer_beerId             int64
beer_brewerId           int64
beer_name              object
beer_style             object
review_appearance     float64
review_palette        float64
review_overall        float64
review_taste          float64
review_profileName     object
review_aroma          float64
review_text            object
review_time             int64
dtype: object

In [7]:
print("\n----------- Minimum -----------\n")
print(beer_df[['beer_ABV', 'review_appearance', 'review_palette', 'review_overall', 'review_taste', 'review_aroma']].min())

print("\n----------- Max -----------\n")
print(beer_df[['beer_ABV', 'review_appearance', 'review_palette', 'review_overall', 'review_taste', 'review_aroma']].max())

----------- Minimum -----------

beer_ABV             0.01
review_appearance    0.00
review_palette       1.00
review_overall       0.00
review_taste         1.00
review_aroma         1.00
dtype: float64

----------- Max -----------

beer_ABV             57.7
review_appearance     5.0
review_palette        5.0
review_overall        5.0
review_taste          5.0
review_aroma          5.0
dtype: float64

In [11]:
beer_dropped_cols = beer_df.drop(columns=['review_time', 'review_text'])
beer_dropped_cols

,beer_ABV,beer_beerId,beer_brewerId,beer_name,beer_style,review_appearance,review_palette,review_overall,review_taste,review_profileName,review_aroma
0,5.0,47986,10325,Sausa Weizen,Hefeweizen,2.5,2.0,1.5,1.5,stcules,1.5
1,6.2,48213,10325,Red Moon,English Strong Ale,3.0,2.5,3.0,3.0,stcules,3.0
2,6.5,48215,10325,Black Horse Black Beer,Foreign / Export Stout,3.0,2.5,3.0,3.0,stcules,3.0
3,5.0,47969,10325,Sausa Pils,German Pilsener,3.5,3.0,3.0,2.5,stcules,3.0
4,7.7,64883,1075,Cauldron DIPA,American Double / Imperial IPA,4.0,4.5,4.0,4.0,johnmichaelsen,4.5
...,...,...,...,...,...,...,...,...,...,...,...
528865,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.0,4.0,3.5,orangemoustache,4.0
528866,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.5,3.0,3.0,MisterStout,3.0
528867,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,4.0,4.5,4.0,meechum,4.5
528868,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,3.0,4.0,4.0,Dodo2step,4.5
528869,NaN,4032,3340,Dinkel Acker Dark,Munich Dunkel Lager,4.0,4.0,4.0,4.0,jenbys2001,4.0

In [12]:
clean_beer = beer_dropped_cols.dropna()
clean_beer

,beer_ABV,beer_beerId,beer_brewerId,beer_name,beer_style,review_appearance,review_palette,review_overall,review_taste,review_profileName,review_aroma
0,5.0,47986,10325,Sausa Weizen,Hefeweizen,2.5,2.0,1.5,1.5,stcules,1.5
1,6.2,48213,10325,Red Moon,English Strong Ale,3.0,2.5,3.0,3.0,stcules,3.0
2,6.5,48215,10325,Black Horse Black Beer,Foreign / Export Stout,3.0,2.5,3.0,3.0,stcules,3.0
3,5.0,47969,10325,Sausa Pils,German Pilsener,3.5,3.0,3.0,2.5,stcules,3.0
4,7.7,64883,1075,Cauldron DIPA,American Double / Imperial IPA,4.0,4.5,4.0,4.0,johnmichaelsen,4.5
...,...,...,...,...,...,...,...,...,...,...,...
528792,5.1,29915,3340,Dinkelacker Goldhï¿½lsle,German Pilsener,4.0,3.5,4.5,4.0,Lexluthor33,4.0
528793,5.1,29915,3340,Dinkelacker Goldhï¿½lsle,German Pilsener,4.0,3.5,3.5,3.5,stoutman,3.5
528794,4.9,32658,3340,Schwaben Pilsner,German Pilsener,3.5,3.5,3.0,3.0,thierrynantes,3.0
528795,4.9,32658,3340,Schwaben Pilsner,German Pilsener,3.0,3.0,3.5,3.0,wl0307,3.0
528796,4.9,32658,3340,Schwaben Pilsner,German Pilsener,3.0,2.5,2.5,2.5,BlackHaddock,2.5

In [15]:
clean_beer.describe()

,beer_ABV,beer_beerId,beer_brewerId,review_appearance,review_palette,review_overall,review_taste,review_aroma
count,508475.000000,508475.000000,508475.000000,508475.000000,508475.000000,508475.000000,508475.000000,508475.000000
mean,7.017467,21822.790013,2534.078684,3.872699,3.769016,3.840857,3.775375,3.827686
std,2.204484,22124.321330,5237.579622,0.601774,0.682371,0.706407,0.665587,0.715133
min,0.010000,5.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000
25%,5.300000,1673.000000,132.000000,3.500000,3.500000,3.500000,3.500000,3.500000
50%,6.500000,13838.000000,392.000000,4.000000,4.000000,4.000000,4.000000,4.000000
75%,8.500000,40418.000000,1315.000000,4.000000,4.000000,4.500000,4.000000,4.500000
max,57.700000,77310.000000,27980.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [40]:
file_path = '/Users/e1/Desktop/Class Folder/BREAKING_SAD/clean_beer.csv'
clean_beer.to_csv(file_path, index=False)